version: '3.9'
services:
  #mongodb:
  #  image: mongo
  #  ports:
  #    - 27017:27017
  #  environment:
  #    MONGO_INITDB_ROOT_USERNAME: admin
  #    MONGO_INITDB_ROOT_PASSWORD: admin
  #mongo-express:
  #  image: mongo-express
  #  profiles:
  #    - dev
  #  ports:
  #    - 8082:8081
  #  environment:
  #    ME_CONFIG_MONGODB_ADMINUSERNAME: admin
  #    ME_CONFIG_MONGODB_ADMINPASSWORD: admin
  #    ME_CONFIG_MONGODB_SERVER: mongodb
  #  depends_on:
  #    - mongodb
  keycloak:
    image: jboss/keycloak
    ports:
      - 8081:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
